# Generated by Django 3.2.8 on 2022-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
    ]
